# Generated by Django 4.0.6 on 2022-08-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='specialskills',
            options={'verbose_name_plural': 'SpecialSkills'},
        ),
        migrations.AlterModelOptions(
            name='workexp',
            options={'verbose_name_plural': 'WorkExperience'},
        ),
    ]
