# Generated by Django 4.0.6 on 2022-08-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactus_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decsription',
            new_name='description',
        ),
    ]
