# Generated by Django 4.0.6 on 2022-08-13 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactus_options_alter_specialskills_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexp',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='workexp',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
