# Generated by Django 4.0.6 on 2022-08-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_workexp_enddate_workexp_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexp',
            old_name='postion',
            new_name='position',
        ),
    ]
