# Generated by Django 4.0.6 on 2022-08-13 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_postion_workexp_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='education',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
