# Generated by Django 4.0.6 on 2022-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_education_enddate_education_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='hist',
            field=models.CharField(choices=[('Junior School', 'Junior'), ('Senior School', 'Senior'), ('Graduate School', 'Graduate')], default='Junior', max_length=50),
        ),
    ]
