# Generated by Django 4.0.6 on 2022-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_education_hist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField(max_length=100)),
                ('skill_percent', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
